name: Update DUF Package

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  update-duf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Latest DUF Version
      id: get_version
      run: |
        LATEST_DUF=$(curl -s https://github.com/muesli/duf/releases/latest | grep -oP 'tag/\K[^\"]+')
        echo "latest_version=${LATEST_DUF}" >> $GITHUB_ENV

    - name: Check Current DUF Version
      run: |
        LOCAL_DUF=$(basename $(find ./Linux/Scripts/Post\ Install/Ubuntu/Packages -name "duf*.deb" 2>/dev/null) | grep -oP '\d+\.\d+\.\d+')
        if [ "$LATEST_DUF" != "$LOCAL_DUF" ]; then
          echo "New version available: $LATEST_DUF. Updating..."
          echo "update_needed=true" >> $GITHUB_ENV
        else
          echo "DUF is up to date."
        fi

    - name: Download New DUF
      if: env.update_needed == 'true'
      run: |
        wget https://github.com/muesli/duf/releases/download/v${{ env.latest_version }}/duf_${{ env.latest_version }}_amd64.deb -O ./Linux/Scripts/Post\ Install/Ubuntu/Packages/duf_${{ env.latest_version }}_amd64.deb
        echo "DUF updated to version $LATEST_DUF."
